---
title: "Syllabus : Economie financière"
author:
  - name: Thomas Delcey
    email: thomdelcey@gmail.com
    affiliations:
      - name: Université de Bourgogne Europe
format:
  html: default 
  pdf: default
---

## Cible

Étudiant.es BUT2
—

# Finalité du cours

Comprendre l’**environnement économique** dans lequel vous allez évoluer et acquérir les bases pour analyser les **inégalités** (mesure, causes, conséquences, politiques publiques).

# Objectifs d’apprentissage 

Ce cours introduit les concepts fondamentaux de l'économie monétaire et financière. 

À l’issue de ce cours, les étudiant.es seront capables de :
1. Expliquer les mécanismes de financement des organisations et le rôle de l’intermédiation financière ;  
2. Comprendre le fonctionnement des principaux marchés financiers et identifier leurs acteurs clés ;  
3. Expliquer les causes et les effets des grandes crises financières, passées et récentes ;  
4. Analyser le rôle de la monnaie et des banques dans le système économique.  

# Organisation et formats d’apprentissage

- **CM (cours magistral)** : 6 heures CM 
- **TD (travaux dirigés)** : 7.5 heures TD


# Plan du cours 

Chaque thématique est abordée à la fois en CM et en TD. Le CM introduit les concepts clefs et le TD se concentre sur les sujets les plus difficiles à appréhender, à travers des études de cas et des exemples pratiques. 

- **Chapitre 1 & 2 :** La finance et ses acteurs (CM) 
  - Le TD associé revient sur les différents titres financiers et marchés associés.
- **Chapitre 3 :** Les crises financières (CM) 
  - Le TD associé propose une explication détaillée de la crise des Subprimes. 
- **Chapitre 4 :** La monnaie et la politique monétaire (CM) 
  - Le TD associé porte sur la création monétaire par les banques commerciales. 
  
## Evaluation

- 1 devoir sur table (100%), ensemble du cours ; questions de réflexion et analyse de données courtes.
