project:
  type: website
  output-dir: docs
  render:
    - "**/*.qmd"
  resources:
    - CNAME

website:
  site-url: "https://thomasdelcey.com/"
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/tdelcey/personal_page
          - text: Report a Bug
            url:  https://github.com/tdelcey/personal_page/issues
    background: primary
    pinned: true 
    left:
      - text: "Home"
        file: index.qmd
      - text: "Research"
        menu:
          - text: "Publications"
            file: publications.qmd
          - text: "Work in progress"
            file: project.qmd
      - file: data.qmd
      - file: teaching.qmd

  page-footer:
   right: 
    - text: "© Thomas Delcey"
      
      
format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
    theme:
      - flatly
      - custom.scss
    css:
      - styles.css
      - assets/slide-viewer.css
    include-in-header: assets/google-fonts.html
    include-after-body: assets/slide-viewer.html

