---
title: "Syllabus : Économie Ecologique"
author:
  - name: Thomas Delcey
    email: thomdelcey@gmail.com
    affiliations:
      - name: Université de Bourgogne
format:
  html: default 
  pdf: default
---


## Cible

Étudiant.es BUT2

## Description et objectifs

Le cours introduit les étudiant.es aux enjeux de la crise écologique. Il vulgarise les points clefs concernant le changement climatique,  les principaux facteurs d'émissions et les enjeux socio-économiques associés à la transition écologique. Le cours est intégré dans un projet de groupe où les étudiant.es analysent l'empreinte carbone d'une entreprise et proposent une solution d'atténuation à travers le cadre de la société à mission. Les étudiant.es sont accompagnés par des intervenants extérieurs spécialistes de l'empreinte carbone et de la RSE. 


Après ce cours, les étudiant.es auront:

1. Une vision globale des enjeux écologiques. 
2. Ils seront capables de comprendre les politiques publiques associées.
3. Ils seront capables de comprendre les enjeux de la transition écologique à l'échelle du consommateur et de l'entreprise.


## Évaluation

- Soutenance orale (projets de groupe).

## Plan et calendrier 

### Fresque pour le climat (en TP)

#### Chapitre 0 : Présentation du projet de groupe

- Directives pour le projet.
- Formation des groupes et choix du sujet.

#### Chapitre 1 : La crise climatique

- Sujet 1.1: Frontières planétaires. 
- Sujet 1.2: Les fondements scientifiques du changement climatique.

#### Chapitre 2 : L’économie et le climat

- Sujet 2.1: Quel pays réchauffe le climat ? 
- Sujet 2.2: Quel secteur réchauffe le climat ? 

#### Chapitre 3 : L’analyse économique de la crise climatique

- Sujet 3.1: La tragédie des communs.
- Sujet 3.2: Les instruments politiques (taxe, tarification, etc.)


## Ressources bibliographiques

Une liste de ressources (articles, vidéos, infographies) sera fournie au début du cours. 

