---
title: "Samuelson vs Fama on the Efficient Market Hypothesis, The Point of View of Expertise"
author: Thomas Delcey
date: "2019"
date-format: "YYYY"
categories: "History of financial economics"
---


## Abstract

This paper investigates the polysemic character of the Efficient Market Hypothesis through a comparison of the contributions of the two authors who introduced this hypothesis in 1965, Eugene Fama and Paul Samuelson. While both had a normative approach, it is argued that the key point distinguishing the two contributions is the expertise developed by each author. Fama interpreted his model to make practical recommendations for investment strategy. Samuelson interpreted his model to discuss and promote a political expertise that would be useful for policymaking such as the Pareto optimality of speculative price or the social benefit of speculation. The second part investigates the context of paper writing. We suggest that two elements are central to explain Fama and Samuelson’s stance. First, the contrasting viewpoints of their research institutions, respectively Chicago and MIT, and second, the position of each author in early financial economics. Finally, we show how their early contrasted stance is consistent with Fama and Samuelson’s opposite reactions to the Efficient Market Hypothesis controversy in the 1980s. In conclusion, we suggest that this opposition between Fama and Samuelson is useful to discuss the early EMH controversy in the 1980s.

## Published In

This article is published in *Œconomia*. [Link](https://doi.org/10.4000/oeconomia.5300)

