---
title: "Syllabus : Économie des inégalités"
format: pdf
---


# Cible

Étudiant.es BUT3

## Objectifs :

1. Maîtriser les concepts fondamentaux liés aux inégalités sociales et économiques.
2. Dresser un état des inégalités économiques dans le monde et en France.
3. Distinguer les enjeux de répartition entre capital et travail et ceux dans le travail. 
4. Présenter les principales politiques de lutte contre les inégalités.

## PLAN

### Chapitre 1 : Introduction 
- Sujet 1.1. Pourquoi lutter contre les inégalités ? 
- Sujet 1.2. Les différentes formes des inégalités.  

### Chapitre 2 : Mesurer les inégalités 
- Sujet 2.1. Introduction aux outils statistiques. 
- Sujet 2.2. Etats des lieux des inégalités économiques

### Chapitre 3 : Inégalités dans la valeur ajoutée 
- Sujet 3.1. La répartition de la valeur entre travail et capital
- Sujet 3.2. Pourquoi les profits augmentent-ils ?

### Chapitre 4 : Inégalités dans le travail 
- Sujet 4.1. Les inégalités hommes-femmes.
- Sujet 4.2. Le numérique et la polarisation du travail 

### Chapitre 5 : Lutter contre les inégalités  
- Sujet 4.1 : Taxer dans une économie mondialisée.
- Sujet 4.2 : Les politiques éducatives en France.  

## Évaluation :
1. Examen de mi-parcours - QCM (séance 5)
2. Examen final : 100% - devoir sur table (séance 9)

## Ressources recommandées :
1. Piketty, T. (2013). "L’économie des inégalités". Edition : La découverte.
2. Milanovic, B. (2016). "Inégalités mondiales". Edition : La découverte.

